[gsheets]
type = "service_account"
project_id = "casita-de-semillas-mau"
private_key_id = "7c000026dacd355437568706494437feb0895a1c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0iDn+/svxF+PP
SFistpLjCx5uskNZcMN5PQhAqMC1tPRjbKwEqaKYFPgedg0rvdU9JyNjoQ5wwKZh
mieSSYxO3vmTbGQNoVsZL91+B84KYqJQtB5iNZ4j+xS+APHF8esLvEwR47+n6UYZ
+aJl+s6xuNihCnP7oXbt6TBvxhBddtyFFPs/sSQUBbKrFB0CLaNgXxj1Y20+NW/L
IDS0/KJpTSxE/we36SL54Jj/YM9FNe5DWoRt27M78tvBE7Jgr59KHWCXQjwFbOX6
QvnAQq8APW06hJrY/INHDTv54+SZTSSvnvvLwBHku49AVMc9gzciDXb8VybLLtEE
0wG/2Io7AgMBAAECggEAJgRd+jXb6qx2O8tnaQ+VhRxtTzBZAHe/okNY/ozK8Djo
EhvraZvzcoVP7tI7Wc/DHPql+DANY28eWoVk+ehlFKLd+c6kjz5AeeBbi1PHbuZw
egBEObhC0h7osk5um5mjPrhraIUGciysp4GrUkBr0H81l0wlOoM5EUa+/Xq/LX8k
wR6T25qFpVI9gZsUyq3TdydjbdI+/7kBiYvNh1hvE5gON5Obeq4Jzxtxp/3tU2uF
xBGCfe/xek96dTys+HC6FfiEXdncWAdXn/GvKQ83ZnG9v22WDZV2yYf8r641qImF
p7+NJR5frPAwvluew4j+fHswOB+py0Sncht4pk5BuQKBgQDdpv86/sTuyER3Dp+n
z+jw8XxHmLhXuQdrCTbFDwfi6YDBiOJBCWpVQuX0SEQXF6IsngfdbgDVYCXQLIeh
iV+lwXALUtYAnCfC16HLi0WRAplRy0/3V5KANF5Nqi+tIn26mEw7oAlSXUm0iP5F
Q8zqUGYmAxMVMbZ/2Rb6Kkx3PwKBgQDQgfsrjvPwS42J93KAs5CK8R+5IfJtph+V
FHgGGXt24Lwwkh6vhtPAK8ejEyl0/FmVBgjCf/eqhxr0+U4NJcgqO0vjDUowupPs
Qsnbe0PuHwI94KD+yKvWPT1i2D915/CFgIgQReodfpSj7f8Gzf7m5lxYYz2ddo0+
/zLvh55KBQKBgHVNGoejKp9ftvP29kE+A333npjZVr19+1IG90hEUx0gC/bgNTTM
Ac0LcVzdHcPGyxmnrGvf+mrxzjEkT8cKR2cWPvCPLxf1jAlOSp7IntFGOdOSsEgq
vSpCDKI3bbHHrhgg3z8yy5weKJJ1aXNIlVpvoA9/0wqFW5q/Tayo0/zLAoGBALEe
aTVENvXdyDr1px+q6VMNpuwF6UC5iESEYbyUsut11obP6R8jwgaRagGeCm5k2tgb
ix9lwwXpxL1qdaH3gURWoI0cQfSI2ZUt2vkFidviHW5gvYIRBt9zoAyyM549y3Qs
jeh863Xoi+2BA01NeYW9E57FlpaHGU71S9hrdMvdAoGBAJDTCQGyimmNY62QidwM
WBtROZTXfw8B5p4Q/3OWDESPiJ5OG6461nbkjMEMlQLPiFIX+lKxIoeL9OY9Eyld
HfD329MCw5+fpUwV15rXccS9Cf2hr+MHG+rGZG9SaFq7fL0qG9H5k2mJhRqoAOZS
vCFkZ+/mkMIcZ0Jf3eltQblz
-----END PRIVATE KEY-----"""
client_email = "casita-semillas-app@casita-de-semillas-mau.iam.gserviceaccount.com"
client_id = "100532056765749137418"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/casita-semillas-app%40casita-de-semillas-mau.iam.gserviceaccount.com"
